name: mod_timecontrol
description: "Becker Timecontrol Module"
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  timecontrol_protocol:
    path: ../../plugins/timecontrol
  
  multi_transport:
    path: ../../plugins/multi_transport/
  
  mt_sock:
    path: ../../plugins/multi_transport/mt_sock

  modules_common:
    path: ../modules_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
