name: translator
description: AI Fueled Translation Tool
version: 0.0.1

environment:
  sdk: ">=3.0.6 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.4.13
dependencies:
  openai_dart: ^0.4.5
  openapi_generator: ^6.1.0
  openapi_generator_annotations: ^6.1.0

