name: modules_common
description: "Collection of various modules shared between modules."
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  archive: ^4.0.1
  intl: ^0.20.2
  vector_math: ^2.1.4
  geolocator: ^14.0.0
  provider: ^6.0.5
  file_picker: ^10.1.9
  flutter_oss_licenses: ^3.0.4
  yaml: ^3.1.2
  collection: ^1.17.1
  ffi: ^2.0.2
  wakelock_plus: ^1.2.2
  window_manager: ^0.5.1
  sqflite_common_ffi: ^2.3.5
  sqflite: ^2.4.2
  http: ^1.2.1
  version: ^3.0.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.1
  path: ^1.9.1
  open_filex: ^4.7.0
  open_settings_plus: ^0.4.0

  
  ui_common:
    path: ../../plugins/ui_common/

  multi_transport:
    path: ../../plugins/multi_transport/

  hydrogen_flutter:
    path: ../../plugins/hydrogen_flutter
    # git: 
    #   url: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.becker-antriebe.com/entwicklung_elektronik/hydrogen_flutter.git
    # git: 
    #   url: https://gitlab.becker-antriebe.com/entwicklung_elektronik/hydrogen_flutter.git
    #   ref: 097d1d5b967e6e8647481ad53c4f7d3f4b5700aa

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

