name: mod_evo
description: "Implementation for the Becker Antriebe EVO BLE Motors."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  modules_common:
    path: ../modules_common

  evo_protocol:
    path: ../../plugins/evo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
