library ui_common;

import 'dart:async' show Completer, Timer;
import 'dart:math' show min, max, pi;
import 'dart:ui' as ui;
import 'dart:io' show File;
import 'dart:collection' show HashMap;
import 'dart:developer' as dev;
// ignore: unused_import
import 'package:collection/collection.dart';
import 'dart:convert' show json;
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';
import 'package:expandable/expandable.dart';
import 'package:provider/single_child_widget.dart';
import 'package:flutter/rendering.dart' show RenderBox, RenderRepaintBoundary;
import 'package:go_router/go_router.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:gettext_parser/gettext_parser.dart' as gettext_parser;
import 'package:i18n_extension/i18n_extension.dart';
import 'package:path_provider/path_provider.dart';

export "package:go_router/go_router.dart";

part 'package:ui_common/i18n/importer.dart';  
part 'package:ui_common/i18n/i18n.dart';
part 'package:ui_common/app/app.dart';
part 'package:ui_common/app/controller.dart';
part 'package:ui_common/app/app_nav_observer.dart';
part 'package:ui_common/scaffold/interceptor.dart';
part 'package:ui_common/scaffold/scaffold.dart';
part 'package:ui_common/scaffold/drawer.dart';
part 'package:ui_common/scaffold/end_drawer.dart';
part 'package:ui_common/scaffold/tile.dart';
part 'package:ui_common/messenger/messenger.dart';
part 'package:ui_common/messenger/defaults.dart';
part 'package:ui_common/messenger/alert.dart';
part 'package:ui_common/messenger/setup_runner.dart';
part 'package:ui_common/popups_overlay/simple_question.dart';
part 'package:ui_common/popups_overlay/pop_over.dart';
part 'package:ui_common/device_controls/big_slider.dart';
part 'package:ui_common/device_controls/big_move.dart';
part 'package:ui_common/device_controls/big_switch.dart';
part 'package:ui_common/form_controls/action.dart';
part 'package:ui_common/form_controls/button.dart';
part 'package:ui_common/form_controls/text_input.dart';
part 'package:ui_common/form_controls/switch.dart';
part 'package:ui_common/form_controls/sliders.dart';
part 'package:ui_common/form_controls/range_slider.dart';
part 'package:ui_common/form_controls/toggle_buttons.dart';
part 'package:ui_common/form_controls/big_name.dart';
part 'package:ui_common/containers/named_container.dart';
part 'package:ui_common/containers/option_list.dart';
part 'package:ui_common/containers/progress_indicator.dart';
part 'package:ui_common/containers/fat_list.dart';
part 'package:ui_common/containers/fat_list_tile.dart';
part 'package:ui_common/containers/info.dart';
part 'package:ui_common/containers/expandable.dart';
part 'package:ui_common/containers/page.dart';
part 'package:ui_common/containers/constrained_sliver_list.dart';
part 'package:ui_common/containers/constrained_column.dart';
part 'package:ui_common/containers/small_tile.dart';
part 'package:ui_common/containers/badge.dart';
part 'package:ui_common/motion_grid/grid.dart';
part 'package:ui_common/motion_grid/dynamic_height.dart';
part 'package:ui_common/motion_grid/motion_view.dart';
part 'package:ui_common/motion_grid/motion_models.dart';
part 'package:ui_common/motion_grid/motion_drag_item.dart';
part 'package:ui_common/motion_grid/motion_item.dart';
part 'package:ui_common/theme/scheme_extension.dart';
part 'package:ui_common/theme/button_styles.dart';
part 'package:ui_common/theme/text_theme_extension.dart';
part 'package:ui_common/theme/light.dart';
part 'package:ui_common/theme/dark.dart';
part 'package:ui_common/common/404.dart';
part 'package:ui_common/common/divider.dart';
part 'package:ui_common/common/spacer.dart';
part 'package:ui_common/common/sliding_page_route_builder.dart';
part 'package:ui_common/common/package_info.dart';
part 'package:ui_common/common/widget_to_image.dart';
part 'package:ui_common/common/async_periodic_timer.dart';
part 'package:ui_common/common/shapes.dart';
part 'package:ui_common/theme/color_extension.dart';
part 'package:ui_common/theme/becker_icons.dart';
part 'package:ui_common/text/copyable.dart';
part 'package:ui_common/text/title.dart';
part 'package:ui_common/graph/line_chart.dart';


typedef QueryParamDef = Map<String, String>;
typedef RouteBuilderDef = Widget Function(dynamic params);