part of 'module.dart';

final Map<String, String> _xcfFaultCodes = {
  "389": "Quittierung nach Neustart der Steuerung".i18n,
  "529": "NA1 NOT-HALT ausgelöst".i18n,
  "530": "NA2 NOT-HALT ausgelöst".i18n,
  "532": "Schlupftür wurde geöffnet".i18n,
  "534": "Torverriegelungsbolzen löst nicht".i18n,
  "535": "Schlupftürverriegelungsbolzen löst nicht".i18n,
  "816": "Schlaffseil/ Überlastschalter ausgelöst".i18n,
  "822": "Negative Testung des elektromagnetisch testbaren Schlupftürschalters".i18n,
  "1792": "Endschalter AUF und ZU zeitgleich belegt".i18n,
  "1793": "Endschalter Teilöffnung und Geschlossen zeitgleich belegt".i18n,
  "1872": "Protokoll Übertragungsfehler des Absolutwertdrehgebers".i18n,
  "1874": "Übertragungsfehler zum Absolutwertdrehgeber des Antriebes".i18n,
  "1875": "Position hat sich sprunghaft geändert".i18n,
  "1894": "Interner Fehler Geber".i18n,
  "2128": "Eingang Sammelstörung".i18n,
  "2320": "Interner NOT-HALT ausgelöst".i18n,
  "2338": "Not-Stopp-Transistor defekt".i18n,
  "2343": "Hardware-Testung der Transistoren Auf, Zu oder Sicherheit fehlgeschlagen".i18n,
  "2353": "Steuerungsinterner Fehler beim ROM-Test".i18n,
  "2354": "Steuerungsinterner Fehler beim RAM-Test".i18n,
  "2416": "Interner Zugriffsfehler auf nichtflüchtigen Speicher (EEPROM)".i18n,
  "2449": "E.020".i18n,
  "32": "Laufzeitüberschreitung in Schließ-Richtung".i18n,
  "33": "Laufzeitüberschreitung in Öffnen-Richtung".i18n,
  "49": "Antriebsdrehrichtung weicht von der erwarteten Drehrichtung ab".i18n,
  "128": "Wartung ist notwendig".i18n,
  "277": "Befehl Stopp zu lange belegt".i18n,
  "278": "Fahrbefehl Schließen zu lange belegt".i18n,
  "279": "Fahrbefehl Öffnen zu lange belegt".i18n,
  "800": "Hindernis blockiert Fahrt".i18n,
  "821": "Schlupftürschalter ungleichmäßig geschaltet".i18n,
  "833": "Einzugsicherung AUF ausgelöst".i18n,
  "834": "Einzugsicherung AUF und ZU ausgelöst".i18n,
  "835": "Einzugsicherung ZU ausgelöst".i18n,
  "836": "Sicherheit OSE FE1 ausgelöst".i18n,
  "848": "Schaltleiste SE1 ist vor der ZU-Fahrt geschaltet".i18n,
  "850": "Negativer Test des Eingangs SE1".i18n,
  "864": "Schaltleiste SE2 ist vor der ZU-Fahrt geschaltet".i18n,
  "866": "Negativer Test des Eingangs SE2".i18n,
  "868": "Kein Schaltimpuls der Schaltleiste in der unteren Endlage – Testung fehlgeschlagen (DW)".i18n,
  "884": "Vorendschalter Schaltleistentestung zu hoch eingestellt".i18n,
  "1032": "Kommunikationsstörung zur Erweiterungskarte M2".i18n,
  "1896": "Batterieunterspannung TST PD".i18n,
  "2049": "Negative Testung der Lichtschranke 1".i18n,
  "2050": "Negative Testung der Lichtschranke 2".i18n,
  "2051": "Negative Testung der Einzugsicherung AUF".i18n,
  "2052": "Negative Testung der Einzugsicherung AUF und ZU".i18n,
  "2053": "Negative Testung der Einzugsicherung ZU".i18n,
  "2054": "Negative Testung der Schaltleiste SE1".i18n,
  "2055": "Negative Testung des Sicherheitseingangs SE2".i18n,
  "2056": "Negative Testung der Schlupftür SE2".i18n,
  "2064": "Funkleiste konnte nicht aktiviert werden".i18n,
  "2129": "Eingang Sammelstörung".i18n,
  "67": "Störung des Vorendschalters für die Lichtschranke".i18n,
  "129": "Ablauf des Wartungsintervalls".i18n,
  "273": "Funktaster Kanal 1 zu lange belegt".i18n,
  "274": "Funktaster Kanal 2 zu lange belegt".i18n,
  "275": "Funktaster Kanal 3 zu lange belegt".i18n,
  "276": "Funktaster Kanal 4 zu lange belegt".i18n,
  "280": "Fahrbefehlfolgetaster zu lange belegt".i18n,
  "281": "Fahrbefehlfolgetaster zu lange belegt".i18n,
  "544": "RWA-Eingang ausgelöst".i18n,
  "849": "Schaltleiste SE1 hat bei 5 aufeinander folgenden Abfahrten ausgelöst".i18n,
  "865": "Schaltleiste SE2 hat bei 5 aufeinander folgenden Abfahrten ausgelöst".i18n,
  "2130": "Eingang Sammelstörung".i18n,
  "2309": "Deckeltastatur ist nicht aufgesteckt".i18n,
};